[package]
name = "lowicoin"
version = "0.1.0"
edition = "2021"

[dependencies]
frankenstein = "0.7"
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.29", features = ["bundled"] }
rand = "0.8"
chrono = "0.4"
paris = "1.5.15"
